import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class MockUserService {
  constructor() {}

  public userData = [
    {
      id: 1,
      img: 'src/assets/user1.png',
      alert: '28',
      winRate: '52%',
      yieldValue: '10%',
      money: '9384',
      moneyOnPlus: true,
      whatRatio: '40%',
      isAuthenticatedUset: true,
      firstName: 'Roger',
      secondName: 'Doe',
      login: 'Roger D',
      userTag: '@rogerd1',
    },
    {
      id: 2,
      img: 'src/assets/user2.png',
      alert: '30',
      winRate: '86%',
      yieldValue: '-10%',
      money: '3397',
      moneyOnPlus: true,
      whatRatio: '56%',
      isAuthenticatedUset: false,
      firstName: 'Liam',
      secondName: 'Miller',
      login: 'Liam M',
      userTag: '@liamm2',
    },
    {
      id: 3,
      img: 'src/assets/user3.png',
      alert: '16',
      winRate: '67%',
      yieldValue: '-8%',
      money: '3275',
      moneyOnPlus: true,
      whatRatio: '56%',
      isAuthenticatedUset: true,
      firstName: 'Alice',
      secondName: 'Brown',
      login: 'Alice B',
      userTag: '@aliceb3',
    },
    {
      id: 4,
      img: 'src/assets/user4.png',
      alert: '41',
      winRate: '72%',
      yieldValue: '15%',
      money: '4995',
      moneyOnPlus: false,
      whatRatio: '18%',
      isAuthenticatedUset: false,
      firstName: 'Liam',
      secondName: 'Smith',
      login: 'Liam S',
      userTag: '@liams4',
    },
    {
      id: 5,
      img: 'src/assets/user5.png',
      alert: '4',
      winRate: '100%',
      yieldValue: '6%',
      money: '3985',
      moneyOnPlus: true,
      whatRatio: '82%',
      isAuthenticatedUset: true,
      firstName: 'John',
      secondName: 'Brown',
      login: 'John B',
      userTag: '@johnb5',
    },
    {
      id: 6,
      img: 'src/assets/user6.png',
      alert: '23',
      winRate: '62%',
      yieldValue: '-18%',
      money: '5677',
      moneyOnPlus: false,
      whatRatio: '20%',
      isAuthenticatedUset: false,
      firstName: 'Liam',
      secondName: 'Smith',
      login: 'Liam S',
      userTag: '@liams6',
    },
    {
      id: 7,
      img: 'src/assets/user7.png',
      alert: '8',
      winRate: '99%',
      yieldValue: '0%',
      money: '3211',
      moneyOnPlus: false,
      whatRatio: '41%',
      isAuthenticatedUset: true,
      firstName: 'Liam',
      secondName: 'Johnson',
      login: 'Liam J',
      userTag: '@liamj7',
    },
  ];
}
